# Generated by Django 5.1.2 on 2026-01-18 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at', 'pk', 'status'], 'verbose_name': 'Article'},
        ),
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, null=True,
        blank=True),
            preserve_default=False,
        ),
    ]
